name: CI/CD Pipeline - Node.js Demo App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests configured"

      # 5️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Export username to ENV
      - name: Set DockerHub username
        run: echo "DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t "$DOCKER_USER/nodejs-demo-app:latest" .

      - name: Push Docker image
        run: docker push "$DOCKER_USER/nodejs-demo-app:latest"

